# Generated by Django 5.2.4 on 2025-07-15 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
