# Generated by Django 5.2.4 on 2025-07-17 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_alter_room_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='descrioption',
            new_name='description',
        ),
    ]
